version: '3'

services:
  database:
    container_name: expense_database
    image: mongo:5
    volumes:
      - db:/data/db
    ports: 
      - "27017:27017"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  api:
    container_name: expense_api
    build:
      context: ./api
      target: build-dev
    volumes:
      - "./api:/var/www/api"
    ports:
      - "3000:3000"

  app:
    container_name: expense_app
    build:
      context: ./app
      target: build-dev
    volumes:
      - "./app:/var/www/app"
    ports:
      - "80:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  db:
